trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: mvn clean install
    displayName: 'Build application'

  - script: mvn test
    displayName: 'Test application'

  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)/target'
      Contents: '**/*.jar'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
    displayName: 'Copy artifact to publish'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'ruan-minhas-financas-app'
    displayName: 'Publish artifact application'